### ISSUE TITLE
Set up rules how to use/cite Mistra

### ISSUE THREAD

**Issue by pb866** [MistraModel/Mistra#12]
We need to decide on rules and state them in the README concerning:
- [ ] citing Mistra, when using the model
- [ ] decide, whether we want to be informed about publications
- [ ] do we request co-authorships under certain circumstances?

This should probably be discussed together with @Mistra-UEA.

**Comment by rs028** [comment]
Yes, it should be discussed with the UEA group. It would be good to put this information in a text file in the main directory.

IMHO:

1. For the moment, probably cite the 2002 JGR papers by Roland, which are the initial description of the model, and maybe the 2012 EST paper, which contains the updated chemical mechanism (until your paper supersedes it). It also depends whether Josue is still working on his paper, which would be the description of the current version.
1. It would be nice if people let us know. We could have a page in the wiki with the list of publications.
1. This is a bit tricky. My opinion is that co-authorship should be requested when run the model is run for somebody else and/or significant contribution is given. What constitutes significant is a bit debatable and probably should be agreed with the main authors. If somebody can take the model and use it on their own, I am happy with just a citation and maybe acknowledgements.

**Comment by pb866** [comment]
I, again (scary!), absolutely agree with you. 
For 1. That can be a living and breathing statement, so we can always update it, if new papers become available.
But, to have at least a slightly different opinion on a minor point. I think this information is best stored in a separate section in the README. There, the info is prominent as soon as you look at the repo. In a text file in the main folder it can get lost and never looked at. Or, we could have a markdown file and link that in the README, but I would prefer the first option.

**Comment by rs028** [comment]
Just common sense man, don't be alarmed :D 
I am okay to have this in the README. We should draft a "protocol" and then send it to @Mistra-UEA people for comments before including it in the repo.

**Comment by rs028** [comment]
It is an unfortunate situation, but unless the issues related to authorship and licensing are somehow resolved, I would not recommend using the model for research projects and/or publications (see the `README.md` file).

If there is a need to cite the model, the published research papers that used Mistra should suffice.
