### ISSUE TITLE
create a Mistra pre-release

### ISSUE THREAD

**Issue by rs028** [MistraModel/Mistra#14]
On completion of the `Mistra pre-release` milestone create a new release. This pre-release is going to be basically the same as the @Mistra-UEA version, with a few tweaks, and the starting point for future development.

Issue #5 does not have to fully completed to do this. The remaining tasks can be moved to the net mileston (`Mistra v9.0`)

**Comment by pb866** [comment]
May I suggest to name it _Mistra-RC1_. I think, Josue already had several beta versions, and I don't think, we will tweak a lot in there. If we find issues, there can always be an RC2 or a version 9.0.x or 9.x later.

**Comment by rs028** [comment]
Good for me. I was actually referring to the `pre-release` option when you draft a new release in github. It just adds a note next to it. You can see it in the KPP-Mistra repo: https://github.com/MistraModel/KPP-Mistra/releases

**Comment by pb866** [comment]
Yes, I would tag the RC1 as pre-release as it is one. That gives you the option to have several named pre-releases (going from alpha, beta releases to RC's). And I would say, by now we're at the RC stage, but it's still a pre-release.

**Comment by rs028** [comment]
RC1 (PR #22) is on-par with the UEA version up until October 2020. Haven't tried to compile/run it.
