### ISSUE TITLE
Licence change

### ISSUE THREAD

**Issue by rs028** [MistraModel/Mistra#6]
Consider whether EUPL is the most appropriate licence for Mistra.

As I understand it, the EUPL was developed by the EU to cover the work of the commission and potentially of other EU funded projects. While nothing prevents its adoption by other projects, it seems an odd choice for Mistra for the following reasons:
- Mistra is scientific software and, by definition, science is international with Engliush as "lingua franca". Therefore it is irrelevant whether the licence is fully compatible with EU law or translated into all the EU languages.
- Most of the users and developers - past and present - of Mistra are, or soon will be, outside the EU. This is not particularly important per se, it just means an EU centered licence is not relevant.
- The choice of EUPL suggests that primary funding was coming from the EU, but this is not the case. Only part of the work by J. Bock between 2015 and 2020 was funded by the EU. Most of the work before 2015 had other funding sources.
- Mistra is distributed with a customized version of KPP, which is licensed under GPLv2. From https://fossa.com/blog/all-about-copyleft-licenses/: “Under a strong copyleft license like GPL, if you redistribute a program that includes GPL code written by others, you must make your entire program available under GPL.” Technically KPP is a separate program, but Mistra cannot work without it. It’s a bit of a grey area and using the same license avoids the potential confusion.
- The EUPL actually allows allow patent use (see https://choosealicense.com/appendix/) which was initially considered by the developers' team as a disqualifying criterium for Mistra.

I think Mistra should be under a licence with global applicability and widely known/understood all over the world, especially within the scientific community. Personally, I think that it would be more appropriate to use either the GPL licence or, if we want to be more permissive, the MIT or BSD licence (see this website https://tldrlegal.com/ for more info).

From personal and public conversations, most of the developers I spoke to don’t really care about the type of license. Among those who expressed an opinion there is a slight preference towards the GPL.

**Comment by pb866** [comment]
I don't have a strong opinion on this. If it's allowed, feel free to change it.

**Comment by rs028** [comment]
I believe that it is allowed, but I will check how to do it properly.

**Comment by rs028** [comment]
Done by PR #23
